### PR TITLE
Support for livewire 3 and  spatie/laravel-backup 9

### PR DESCRIPTION
**Pull request by MusheAbdulHakim**

### CODE REVIEW

**Comment by pavel-mironchik** [comment]
Thanks for the PR, @MusheAbdulHakim!

Though I'm not merging it, I've got several insights from your work. Would you please try the [2.6.0 branch](https://github.com/pavel-mironchik/laravel-backup-panel/tree/v2.6.0) and tell me if it works without issues?

**Comment by MusheAbdulHakim** [comment]
ok cool.

**Comment by MusheAbdulHakim** [comment]
I have successfully installed and used the 2.60 branch.
For information sake, I am using **"php": "^8.2", and "laravel/framework":11.15.0**. I am also on linux

**Comment by pavel-mironchik** [comment]
Thanks @MusheAbdulHakim!

I will publish a new release soon.

**Pull request closed without merging**
